### ISSUE TITLE
Crashes on Android 5 - Agora v2.9.1

### ISSUE THREAD

**Issue by Apollo122** [AgoraIO/Advanced-Video#101]
Here is the stack trace. Could you please fix it ASAP? We would like to update to latest version.
I redacted the package name to .***.***
But it's all the same.

`10-10 15:35:02.211 18411-18411/com.***.*** D/agora-raw-data-plugin: loadAgoraRtcEnginePlugin
10-10 15:35:02.221 18411-18411/com.***.*** A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 18411 (com.***.***)
10-10 15:35:02.276 18411-20098/com.***.*** V/MediaPlayer-JNI: isPlaying: 1
10-10 15:35:02.276 18411-20098/com.***.*** V/MediaPlayer-JNI: getCurrentPosition: 4341 (msec)
10-10 15:35:02.276 18411-20098/com.***.*** V/MediaPlayer: getDuration_l
10-10 15:35:02.276 2159-2159/? V/MediaPlayerService: getDuration
10-10 15:35:02.276 2159-2159/? V/MediaPlayerService: [18] getDuration = 6059
10-10 15:35:02.276 18411-20098/com.***.*** V/MediaPlayer-JNI: getDuration: 6059 (msec)
10-10 15:35:02.276 18411-20098/com.***.*** V/MediaPlayer: getDuration_l
10-10 15:35:02.276 2159-6377/? V/MediaPlayerService: getDuration
10-10 15:35:02.276 2159-6377/? V/MediaPlayerService: [18] getDuration = 6059
10-10 15:35:02.276 18411-20098/com.***.*** V/MediaPlayer-JNI: getDuration: 6059 (msec)
10-10 15:35:02.276 18411-20098/com.***.*** V/MediaPlayer-JNI: isPlaying: 1
10-10 15:35:02.291 2155-2155/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-10 15:35:02.291 2155-2155/? I/DEBUG: Build fingerprint: 'samsung/j2ltejv/j2lte:5.1.1/LMY47X/J200FXXU3AQL1:user/release-keys'
10-10 15:35:02.291 2155-2155/? I/DEBUG: Revision: '4'
10-10 15:35:02.291 2155-2155/? I/DEBUG: ABI: 'arm'
10-10 15:35:02.291 2155-2155/? I/DEBUG: pid: 18411, tid: 18411, name: com.***.***  >>> com.***.*** <<<
10-10 15:35:02.291 2155-2155/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4
10-10 15:35:02.346 2155-2155/? I/DEBUG:     r0 84c48430  r1 00000004  r2 00000000  r3 83d2ce21
10-10 15:35:02.346 2155-2155/? I/DEBUG:     r4 b6df9df4  r5 76f914f8  r6 13d8e900  r7 becd0b40
10-10 15:35:02.346 2155-2155/? I/DEBUG:     r8 1392a780  r9 b4427800  sl 13aaab40  fp 0000016d
10-10 15:35:02.346 2155-2155/? I/DEBUG:     ip 84c48430  sp becd0b18  lr 8fa756b9  pc 83d2ce3a  cpsr 60070030
10-10 15:35:02.346 2155-2155/? I/DEBUG: backtrace:
10-10 15:35:02.346 2155-2155/? I/DEBUG:     #00 pc 00083e3a  /data/app/com.***.***-1/lib/arm/libagora-rtc-sdk-jni.so
10-10 15:35:02.346 2155-2155/? I/DEBUG:     #01 pc 0000c6b7  /data/app/com.***.***-1/lib/arm/libapm-plugin-raw-data-api-java.so (_ZN5agora4util7AutoPtrINS_5media12IMediaEngineEE14queryInterfaceINS_3rtc10IRtcEngineENS_17INTERFACE_ID_TYPEEEEbPT_T0_+70)
10-10 15:35:02.346 2155-2155/? I/DEBUG:     #02 pc 0000c3e7  /data/app/com.***.***-1/lib/arm/libapm-plugin-raw-data-api-java.so (Java_io_agora_rtc_plugin_rawdata_MediaPreProcessing_setCallback+90)
10-10 15:35:02.346 2155-2155/? I/DEBUG:     #03 pc 02133019  /data/dalvik-cache/arm/data@app@com.***.***-1@base.apk@classes.dex
10-10 15:35:03.166 2159-20078/? I/NuPlayerDecoder: End of Stream
10-10 15:35:03.166 2159-20078/? I/NuPlayerDecoder: End of Stream
10-10 15:35:03.346 2159-20074/? I/NuPlayerRenderer: onQueueEOS audio finalResult : -1011
10-10 15:35:03.706 2159-20074/? I/NuPlayerRenderer: [audio] notifyEOS() End of Stream, delayUs : 340990
10-10 15:35:03.706 2159-20074/? V/AudioSink: stop
10-10 15:35:04.051 2159-20072/? I/NuPlayerRenderer: reachedAudioEOS (1)
10-10 15:35:04.051 2159-20072/? V/NuPlayer: reached audio EOS
10-10 15:35:04.061 2159-2414/? D/AudioSAEffectSec: EffectRelease - session 165
10-10 15:35:04.061 2159-2414/? D/AudioSAEffectSec: EffectRelease : All effects are no longer instantiated
10-10 15:35:04.061 2159-2414/? D/AudioSAEffectSec: AudioSAEffectSec::releaseSA 
10-10 15:35:04.061 2159-2414/? D/AudioSASec: AudioSASec::Close 
10-10 15:35:04.061 2159-2414/? D/AudioSAEffectSec: AudioSAEffectSec::~AudioSAEffectSec 
10-10 15:35:04.061 2159-2414/? D/AudioSASec: AudioSASec::~AudioSASec() + 
10-10 15:35:04.061 2159-2414/? D/AudioSASec: Samsung_SoundAlive_play_Factory::Destroy(mSoundAlive)
10-10 15:35:04.061 2159-2414/? D/AudioSASec: AudioSASec::~AudioSASec() - 
10-10 15:35:04.061 2159-2414/? W/MySoundEffect: MySoundEffect_setEnabled() MySound is already disabled
10-10 15:35:04.061 2159-2414/? D/MySoundEffect: EffectRelease : All effects are no longer instantiated
10-10 15:35:04.061 2159-2414/? D/MySound: MySound::Close 
10-10 15:35:04.061 2159-2414/? D/MySoundEffect: MySoundEffect::~MySoundEffect 
10-10 15:35:04.066 2159-2414/? W/MySpaceEffect: MySpaceEffect_setEnabled() MySpace is already disabled
10-10 15:35:04.066 2159-2414/? D/MySpaceEffect: EffectRelease : All effects are no longer instantiated
10-10 15:35:04.066 2159-2414/? D/MySpace: MySpace::Close 
10-10 15:35:04.066 2159-2414/? D/MySpaceEffect: MySpaceEffect::~MySpaceEffect 
10-10 15:35:04.066 2159-2414/? I/AudioPolicyManager: stopOutput() output 2, stream 3, session 165
10-10 15:35:04.066 2159-2414/? I/AudioPolicyManager: changeRefCount() stream 3, count 0
10-10 15:35:04.066 2159-2414/? I/AudioPolicyManager: setOutputDevice() setting same device 0000 or null device for output 2
10-10 15:35:04.351 2665-2928/? E/NativeCrashListener: Exception dealing with report
    android.system.ErrnoException: read failed: EAGAIN (Try again)
        at libcore.io.Posix.readBytes(Native Method)
        at libcore.io.Posix.read(Posix.java:165)
        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:230)
        at android.system.Os.read(Os.java:350)
        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
10-10 15:35:04.666 2665-2785/? D/CustomFrequencyManagerService: releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1105000  uid : 1000  pid : 2665  tag : ACTIVITY_RESUME_BOOSTER@6
10-10 15:35:04.666 2665-2785/? D/ActivityManager: mDVFSHelper.release()`

**Comment by plutoless** [comment]
which demo are you talking about?

**Comment by TongJiangyong** [comment]
it happend necessary or just in special conditions ?

**Comment by Apollo122** [comment]
It happens all the time.

**Comment by TongJiangyong** [comment]
Hi Apollo122
    could you make sure you have put all our sdk file into the project? because the project "Capture-Raw-Video-Data" also need add the C++ head files  which we provide in our sdk , and make sure those head files is the same version as the jar file and dynamic library

**Comment by Apollo122** [comment]
Ah yes. We copied the files from sdk to Capture-Raw-Video-Data projects, it works now.
Thanks!
