### ISSUE TITLE
 No audio when answer from background

### ISSUE THREAD

**Issue by PrashantKT** [AgoraIO/Advanced-Video#105]
Hey There 

I am facing the weird issue , sometime audio is not coming during the video call I am using Agora RTC Engine 

This is the code I am using 

```
 rtcEngine = AgoraRtcEngineKit.sharedEngine(withAppId: KeyCenter.AppId, delegate: self)
        rtcEngine.setChannelProfile(.communication)
        rtcEngine.enableVideo()
        rtcEngine.enableAudio()
        
        rtcEngine.setDefaultAudioRouteToSpeakerphone(true)
        rtcEngine.setVideoSource(videoSource)
        
        let videoConfig:AgoraVideoEncoderConfiguration = .init(size:self.view.frame.size, frameRate: .fps15, bitrate: 600, orientationMode: .fixedPortrait)
        
        rtcEngine.setVideoEncoderConfiguration(videoConfig)
        
        
        
        let code = rtcEngine.joinChannel(byToken: nil, channelId: roomName, info: nil, uid: UInt(selfSession.userID)) {[weak self] (message, id, elapsed) in
            guard let `self` = self else {return }
            self.selfSession = ARDrawingSession(userID: Int64(id))
            self.selfSession.calls.appendNewCall(call: self.call)
            self.toggleARViewForScreenSharingType()
        }
        
        if code != 0 {
            DispatchQueue.main.async(execute: {
                self.showAlert(withMessage: "Join channel failed: \(code)")
            })
        }
        
        
        rtcEngine.setEnableSpeakerphone(true)

```

When issue occurs it continually occurs several times 

This is the 5da57eef82a646bb00001f05 record ID from agora analysis console   

Am I missing anything ?

**Comment by PrashantKT** [comment]
@plutoless  Any update on this , I am getting  delegate method called with following 
  /** 1012: Audio Device Module: An error occurs in starting the recording device. */
    AgoraErrorCodeAdmStartRecording = 1012,

**Comment by plutoless** [comment]
i think the error code has explained that there's sth wrong with your mic?

**Comment by PrashantKT** [comment]
@plutoless  No mic is fine, This issue doesn't occur every time  , both audio is correctly listenable in most cases.

**Comment by plutoless** [comment]
you are talking about answering incoming phone calls? audio recording will be stopped by system in this case.

**Comment by PrashantKT** [comment]
@plutoless  Nope, When VOIP push received  , then I show Callkit view and on accept the phone call I joined the rtc channel. which is working as expected but if device is locked and user try to accept the phone audio is not working.  Hope you are getting my point
