### ISSUE TITLE
Can't login into the Android app

### ISSUE THREAD

**Issue by himanshujbd** [AgoraIO/Advanced-Video#125]
I have downloaded the Android- Openduo project of Agora and read all the documentation and also i managed to run this app successfully on my android device but in the login activity it asks me to enter the "Please input your account" in numeric only, i entered some random digits but couldn't be able to login. I don't know what account  i should input in the edit text. I tried to contact with Agora team but their team giving me irrelevant replied in two or three days. Please help solve me this issue, i am attaching the screenshot of the error. SO please have a look at it.
<img width="330" alt="output" src="https://user-images.githubusercontent.com/22277357/70884192-48643300-1ffb-11ea-99b4-14c836911d4b.png">

**Comment by plutoless** [comment]
have you turned on token feature for your appid? try turning it off.

**Comment by himanshujbd** [comment]
thanks but may i know how to turn it off? because there is no such option.
Thanks & Regards

-- Himanshu Verma
*   (Software Engineer | ML & Data Science Enthusiast)*

**Comment by plutoless** [comment]
@himanshujbd  the easiest way - just create a new project in your dashboard and make sure you don't turn on token feature (there should be a checkbox there)

**Comment by himanshujbd** [comment]
thanks it worked, i really appreciate it
Thanks & Regards

-- Himanshu Verma
*   (Software Engineer | ML & Data Science Enthusiast)*
