### ISSUE TITLE
Cannot integrate raw-data-api-java module

### ISSUE THREAD

**Issue by AbhijithEnfinTechnologies** [AgoraIO/Advanced-Video#126]
Build command failed.
Error while executing process C:\Users\cmake.exe with arguments {--build D:\raw-data-api-java\.cxx\cmake\debug\armeabi-v7a --target apm-plugin-raw-data-api-java}

D:\raw-data-api-java\src\main\cpp\media_preprocessing_plugin_jni.cpp:4:10: fatal error: 'include/IAgoraMediaEngine.h' file not found

#include "include/IAgoraMediaEngine.h"

         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1 error generated.

ninja: build stopped: subcommand failed.

**Comment by plutoless** [comment]
please follow the instructions in readme,
```
Next Download the Agora Video SDK from Agora.io SDK; Unzip the downloaded SDK package; Copy the .jar files under libs folder to app/libs of this sample project; Copy arm64-v8a/x86/armeabi-v7a" under libs folder to app/src/main/jniLibs of this sample project Copy all files under include folder to raw-data-api-java/src/main/cpp/include of this sample project.
```

you may forget to copy the include files

**Comment by AbhijithEnfinTechnologies** [comment]
Ok. I missed those lines thanks bro it's resolved . Now showing another error when initialize RtcEngine can u tell me why . This is the error
