### ISSUE TITLE
App crashed due to virtual method 'io.agora.rtc.mediaio.IVideoFrameConsumer com.agora.arcore.AgoraVideoSource.getConsumer()

### ISSUE THREAD

**Issue by amtjoshi** [AgoraIO/Advanced-Video#130]
i am getting this exception
    java.lang.NullPointerException: Attempt to invoke virtual method 'io.agora.rtc.mediaio.IVideoFrameConsumer com.agora.arcore.AgoraVideoSource.getConsumer()' on a null object reference
        at com.agora.arcore.AgoraARCoreActivity.sendARView(AgoraARCoreActivity.java:654)
        at com.agora.arcore.AgoraARCoreActivity.access$1200(AgoraARCoreActivity.java:66)
        at com.agora.arcore.AgoraARCoreActivity$13.onPixelCopyFinished(AgoraARCoreActivity.java:643)

**Comment by plutoless** [comment]
![image](https://user-images.githubusercontent.com/471561/72219396-a0517380-3580-11ea-8c73-6d6bd7ea0ad9.png)
looks like your initRtcEngine was not called so video source is not initialized. looking at above code i guess you are not granting proper privileges

**Comment by NowyXC** [comment]
我在Agora-Screen-Sharing-Android项目中也遇到这个问题。
这个项目中不包含initRtcEngine()这段代码。
只有如下代码：
```
 if (checkSelfPermission(REQUESTED_PERMISSIONS[0], PERMISSION_REQ_ID) &&
                checkSelfPermission(REQUESTED_PERMISSIONS[1], PERMISSION_REQ_ID) &&
                checkSelfPermission(REQUESTED_PERMISSIONS[2], PERMISSION_REQ_ID)) {
            initView();
        }
```

**Comment by plutoless** [comment]
@NowyXC  崩溃栈发下吧

**Comment by NowyXC** [comment]
```
io.agora.rtc.ss.app:screensharingsvc D/ScreenSharingService: onFrameAvailable ImgTexFrame{mFormat=ImgTexFormat{mColorFormat=3, mWidth=1200, mHeight=1836}, mTextureId=1, mTexMatrix=[1.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0]}
io.agora.rtc.ss.app:screensharingsvc W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'void io.agora.rtc.mediaio.IVideoFrameConsumer.consumeTextureFrame(int, int, int, int, int, long, float[])' on a null object reference
io.agora.rtc.ss.app:screensharingsvc W/System.err:     at io.agora.rtc.ss.impl.ScreenSharingService$2.onFrameAvailable(ScreenSharingService.java:93)
io.agora.rtc.ss.app:screensharingsvc W/System.err:     at io.agora.rtc.ss.impl.ScreenSharingService$2.onFrameAvailable(ScreenSharingService.java:79)
io.agora.rtc.ss.app:screensharingsvc W/System.err:     at io.agora.rtc.ss.gles.SrcConnector.onFrameAvailable(SrcConnector.java:42)
io.agora.rtc.ss.app:screensharingsvc W/System.err:     at io.agora.rtc.ss.impl.ScreenCapture$2.onDrawFrame(ScreenCapture.java:314)
io.agora.rtc.ss.app:screensharingsvc W/System.err:     at io.agora.rtc.ss.gles.GLRender.drawFrame(GLRender.java:296)
io.agora.rtc.ss.app:screensharingsvc W/System.err:     at io.agora.rtc.ss.gles.GLRender.access$300(GLRender.java:23)
io.agora.rtc.ss.app:screensharingsvc W/System.err:     at io.agora.rtc.ss.gles.GLRender$5.handleMessage(GLRender.java:379)
io.agora.rtc.ss.app:screensharingsvc W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
io.agora.rtc.ss.app:screensharingsvc W/System.err:     at android.os.Looper.loop(Looper.java:150)
io.agora.rtc.ss.app:screensharingsvc W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
io.agora.rtc.ss.app:screensharingsvc E/ScreenCapture: Draw frame failed, ignore
```
上面的异常在以下代码抛出：
 ```
mSCS.getConsumer().consumeTextureFrame(
                        frame.mTextureId,
                        AgoraVideoFrame.FORMAT_TEXTURE_OES,
                        frame.mFormat.mWidth,
                        frame.mFormat.mHeight,
                        0, frame.pts, frame.mTexMatrix);
```
mSCS.getConsumer() 为null

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Advanced-Video/blob/26e5386d8ad6852997c4ebe51627e6d13df18015/Augmented-Reality/Agora-Video-With-ARCore/Agora-ARCore/app/src/main/java/com/agora/arcore/AgoraVideoSource.java#L16
试试在这里打断点看一下

**Comment by NowyXC** [comment]
项目不一样，我测试的项目是Agora-Screen-Sharing-Android
链接：https://github.com/AgoraIO/Advanced-Video/tree/26e5386d8ad6852997c4ebe51627e6d13df18015/Screensharing/Agora-Screen-Sharing-Android
项目中的ScreenCaptureSource.onInitialize(IVideoFrameConsumer observer)也没有在此项目中被调用。唯一能找到相关联的代码如下：
```
if (mRtcEngine.isTextureEncodeSupported()) {
            mSCS = new ScreenCaptureSource();
            mRtcEngine.setVideoSource(mSCS);
        } else {
            throw new RuntimeException("Can not work on device do not supporting texture" + mRtcEngine.isTextureEncodeSupported());
        }
```

**Comment by plutoless** [comment]
一样的，找到这里打下断点
https://github.com/AgoraIO/Advanced-Video/blob/bad1757936612e89eee4ee60772126cd1ceae9e7/Screensharing/Agora-Screen-Sharing-Android/screensharing/src/main/java/io/agora/rtc/ss/impl/ScreenCaptureSource.java#L13

**Comment by NowyXC** [comment]
ScreenCaptureSource类中的onInitialize(IVideoFrameConsumer observer)未被调用。
getConsumer()返回为null。

**Comment by brianxcli** [comment]
No such crash occurred for me. In order to track the issue, you may try the following:
1. Take a look at the agora sdk you use, remember to use video sdk rather than an audio sdk pack;
2. Check whether the method ScreenCaptureSource.onInitialize() is called sometime later. If yes, try not to call consumer before that;
3. Make sure you joined the channel successfully;
4. Post the recent sdk log if you are still not sure why.

**Comment by NowyXC** [comment]
我使用的是SDK是通过JCenter导入的。
1. 在libagorartc库中导入：
`api 'io.agora.rtc:full-sdk:2.9.2'`
2.ScreenSharingService.onFrameAvailable()是会被重复调用的，但是consumer一直为空。
3.ScreenCaptureSource.onInitialize()未在此项目中被调用，请问 mRtcEngine.setVideoSource(mSCS);内部会不会调用此方法？
4.Agora-Screen-Sharing-Android是否不兼容jcenter导入的方式？
5.Agora-Screen-Sharing-Android是否完整的可运行项目？

**Comment by brianxcli** [comment]
运行的项目代码有经过修改吗？
1. 项目兼容 jcenter，你的引入方式没问题；
2. RtcEngine.setVideoSource() 不会直接回调 onInitialzed() 方法，是在视频模块初始化之后调用的；
3. 这个项目是完整可直接运行的。

**Comment by NowyXC** [comment]
1.运行的项目代码只修改了build.gradle，导入rtc的sdk,没有进行过其他修改。
2.此项目中没有找到调用onInitialize()方法的代码。
运行设备为：华为平板M2-801W

**Comment by brianxcli** [comment]
如果允许可以使用其它手机等测试一下。

**Comment by NowyXC** [comment]
使用vivo手机进行测试，与华为平板效果一样，consumer依然为空。此项目是否缺少了IVideoFrameConsumer相关的实现代码。

**Comment by NowyXC** [comment]
发现问题了，声网频道未加入导致。
处理步骤：
1.替换strings.xml中的label_channel_name(频道名)为自己开通的频道名称，原来默认是ss_test
2.在加入频道相关代码中添加生成的临时token

**Comment by plutoless** [comment]
感谢 这块我们看一下怎么可以提升一下体验
