### ISSUE TITLE
how to add watermark text to video files results cloud recording ?

### ISSUE THREAD

**Issue by unangwarsodi** [AgoraIO/Advanced-Video#134]

**Comment by plutoless** [comment]
i think you can add watermark after the video files are recorded?

**Comment by unangwarsodi** [comment]
it's not possible, is there a way to add a watermark to the file recording the cloud without having to edit the recording file?

**Comment by unangwarsodi** [comment]
I found the addVideoWatermart function, but that is only for Live Broadcast, can it be implemented in a videocall?

**Comment by plutoless** [comment]
@unangwarsodi yes. but as you said it only works when you do a live broadcasting, i.e. publishing to CDN RTMP. you can also record that though

**Comment by plutoless** [comment]
@unangwarsodi try this api out
https://docs.agora.io/cn/Voice/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/addVideoWatermark:options:
