### ISSUE TITLE
java.lang.SecurityException: This PhoneAccountHandle is not registered for this user!

### ISSUE THREAD

**Issue by TieuNhi95** [AgoraIO/Advanced-Video#140]
[Agora-RTC-With-ConnectionService-Android]
when addNewIncomingCall called, it throw a exception, i don't know how to fix it.

**Comment by guohai** [comment]
Does it happen on all the device or some?

**Comment by guohai** [comment]
Does it happen on all the device or some?

**Comment by TieuNhi95** [comment]
> Does it happen on all the device or some?

i think it happen on all devices.

**Comment by guohai** [comment]
Please make sure if `registerPhoneAccount` called successfully with this phone account?

Can you debug on that?
