### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by nitinbagdi20** [AgoraIO/Advanced-Video#141]
Error: RTM Login failed <account name entered> LOGIN_ERR_INVALID_TOKEN
please guide me how to fix this.

**Comment by plutoless** [comment]
hi as the error message shows you are using an invalid token.
you may choose to use a project w/o token feature on, or you can use your dashboard to calculate a temp token for rtm login.

**Comment by nitinbagdi20** [comment]
Sir, actually I am using heroku for generating token. I have registered the app id and certificate on heroku and now I am using your source with my app id. Guide me please further if I have missed something.

**Comment by plutoless** [comment]
could you pls share me a token you have generated. i can take a look to see what could go wrong.
