### ISSUE TITLE
Latest sdk not working in 32 bit devices

### ISSUE THREAD

**Issue by RijoshEnfin** [AgoraIO/Advanced-Video#142]
I used latest sdk . Properly working in 64 bit architecture devices  .but 32 bit architucture device not working. "An UnsatisfiedLinkError couldn't find "libapm-plugin-raw-data- api-java.so " Can you help me

**Comment by RijoshEnfin** [comment]
![rsz_screenshot_from_2020-03-06_10-34-33](https://user-images.githubusercontent.com/60249731/76055753-8dfd2000-5f9a-11ea-99af-2da93227d27c.png)

**Comment by plutoless** [comment]
i think you need to adjust your abifilters

**Comment by RijoshEnfin** [comment]
How?

**Comment by plutoless** [comment]
@RijoshEnfin which demo are you running with?

**Comment by RijoshEnfin** [comment]
Repository name: advanced video / Agora-Plugin-Raw-Data-API-Android-Java .but now that repository was  missing.

**Comment by plutoless** [comment]
@RijoshEnfin it's moved here now https://github.com/AgoraIO/Advanced-Video/tree/dev/backup
i will try it out from my end today.

**Comment by plutoless** [comment]
@RijoshEnfin can you change your app/build.gradle file to change the abifilter value to armeabi-v7a

**Comment by RijoshEnfin** [comment]
armeabi-v7a is  working fine  . But  armeabi-v7a  signed apk can't be uploaded to PlayStore.
 how to upload armeabi-v7a  apk  in playstore

**Comment by guohai** [comment]
Hi, can you set `abiFilters 'armeabi-v7a', 'arm64-v8a'` like this?

After the apk generated, you can check if the *.so files locates under arm64-v8a folder.

Thanks

**Comment by RijoshEnfin** [comment]
abiFilters 'armeabi-v7a', 'arm64-v8a' it is working .thanks
