### ISSUE TITLE
Cannot find AR Kit or documentation

### ISSUE THREAD

**Issue by sergiogcharles** [AgoraIO/Advanced-Video#159]
Is there a reference to the AR Kit that Agora.io claims to have implemented, namely "AR Filters and Stickers"? The description is as follows: Apply 600+ animated stickers, magic mirror and color filters. Take control of everything from UI to stream size and support third-party add-ons like filter, encryption, facial recognition, emojis, and more.

I have tried to find documentation on these AR Filters and Stickers; however, I haven't come across anything as yet. The closest I can find to this is a remote assistance AR app on Agora's Medium page.

**Comment by plutoless** [comment]
we have third party vendors supporting this, usually you will need to integrate their sdk together with agora sdk. where did you find the claim?

**Comment by sergiogcharles** [comment]
Hi Qianze, thanks for your fast response! Do you mind providing me a reference to such an SDK? I saw this on the Agora home page here: 
<img width="1108" alt="Screen Shot 2020-04-05 at 6 17 11 PM" src="https://user-images.githubusercontent.com/35356586/78511317-b4fd6c00-7769-11ea-8bf4-501212ae50c8.png">
