### ISSUE TITLE
Audio for LocalVideoInput

### ISSUE THREAD

**Issue by EpariNigam** [AgoraIO/Advanced-Video#164]
How can I send audio along with video in Local Video Input?

**Comment by plutoless** [comment]
take a look at here for custom audio
https://github.com/AgoraIO/Advanced-Audio/tree/master/Android/sample-custom-recorder

**Comment by EpariNigam** [comment]
Thanks. But, what I want is, I want to stream a video file with audio also.
Is there any way, or do I need to use video stream and audio stream
separately?

**Comment by plutoless** [comment]
you have to do it separately.
