### ISSUE TITLE
Call is not receiving on other end

### ISSUE THREAD

**Issue by sujith123** [AgoraIO/Advanced-Video#170]
I have used Calling with ConnectionService Sample app, I can make call form one end but the call is not receiving on other end. I can here ringing sound in calling end.

**Comment by Apiphoom** [comment]
Did you enable video ?

**Comment by sujith123** [comment]
Yes enabled, It is happening in the Samsung tabA. Video from tab is
decoding in other device but the video from other end not decoding in
Samsung TabA
*Thanks & Regards,*
*Sujith K S*

**Comment by plutoless** [comment]
could you pls provide me a channel name and time when it happened?
