### ISSUE TITLE
sample-raw-data运行问题

### ISSUE THREAD

**Issue by junhaiyang** [AgoraIO/Advanced-Video#172]
本地运行  sample-raw-data 、lib-raw-data、lib-component 三个模块的app，完全没有执行 loadAgoraRtcEnginePlugin 和 unloadAgoraRtcEnginePlugin 方法，怎么回事？？？

**Comment by LichKing-2234** [comment]
clone demo后什么都没有修改么

**Comment by saxon134** [comment]
我也遇到这个问题。
clone后，只改了app id，在回调里加了打印。运行后画面都是正常的，就是没有回调：onCaptureVideoFrame、onRenderVideoFrame等
我是已观众身份加入channel的

**Comment by saxon134** [comment]
> clone demo后什么都没有修改么
请问这个问题有进展不？

**Comment by saxon134** [comment]
> clone demo后什么都没有修改么

请问这个问题有进展么？

**Comment by plutoless** [comment]
@saxon134 麻烦确认下回调打印加在哪里

**Comment by brianxcli** [comment]
@junhaiyang @saxon134 请使用 sdk v3.0.1.1
