### ISSUE TITLE
android - unable to share both screen and video streams at a time

### ISSUE THREAD

**Issue by sathish-xe** [AgoraIO/Advanced-Video#176]
I want to share the screen while the video call is running. 
Currently, it stops the video call and changes the video source.
Is there a way to send multiple video streams / tracks from a single client to a channel?

**Comment by plutoless** [comment]
you will need to start a second process creating a new sdk instance.

**Comment by sathish-xseed** [comment]
Should I create two RtcEngine instances then join same channel?
In one client enableVideo() on the other enable screen share?

**Comment by sathish-xseed** [comment]
@plutoless 
Thanks, Got it! 
From
`RtcEngine.create(getApplicationContext(), getString(R.string.agora_app_id), mHandler);`
to this
`RtcEngine mRtcEngine = new RtcEngineImpl(getApplicationContext(), getString(io.agora.advancedvideo.R.string.agora_app_id), mHandler);`

**Comment by saikiran91** [comment]
Declare and initialize two RTCEngine instances with the same app id. eg: "mRtcEngine1" and "mRtcEngine2". Use one instance for video and other for screen share.

**Comment by plutoless** [comment]
@sathish-xseed  our current sdk is single instance - so what you did may not work. if you call create api you will always get the same instance, so you will need to start a second process and create an instance there.

**Comment by sathish-xseed** [comment]
@plutoless Currently, Created my first instance using `RtcEngine.create()` and second instance using `new RtcEngineImpl();`
Do you have any best way to do this?

**Comment by plutoless** [comment]
@sathish-xseed  maybe you can take a look at this https://github.com/AgoraIO/Advanced-Video/tree/dev/backup/Screensharing/Agora-Screen-Sharing-Android

**Comment by sathish-xseed** [comment]
@plutoless [this](https://github.com/AgoraIO/Advanced-Video/tree/dev/backup/Screensharing/Agora-Screen-Sharing-Android) sample has single RtcEngine. When you enable screen share while the local video is getting streamed. It replaces the local video stream with screen share stream. I couldn't find any code which relates to multiple `RtcEngine`

**Comment by sathish-xseed** [comment]
https://docs.agora.io/en/faq/switch_screen_camera_web This web example explains how to have two clients. But in android, I couldn't find one. Right now, I implemented this way https://github.com/AgoraIO/Advanced-Video/issues/176#issuecomment-625236048. I just wanted to know is this best way to go? @plutoless

**Comment by plutoless** [comment]
what i provided has two clients. @sathish-xe see my above comments

**Comment by sathish-xe** [comment]
@plutoless 
Thanks for the sample project.
Now, I'm facing a issue on web.
Screen share stream works only between the mobile devices. Consuming the same stream using the web SDK is not playing the video. But I'm getting the event in `stream-added` subscribing to it successfully.

**Comment by plutoless** [comment]
ensure you call https://docs.agora.io/en/Voice/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/enableWebSdkInteroperability: on your native end

**Comment by shivchand** [comment]
Hi 
I am facing issue with screen share on Android.

I am implementing it with video call and screen share option both.

There is a bindVideoService method when It is called, It donot show local camera video too.

Please let me know if anyone has done it?

**Comment by plutoless** [comment]
@shivchand if you want to do both at the same time, take a look at [this](https://github.com/AgoraIO/Advanced-Video/tree/dev/backup/Screensharing/Agora-Screen-Sharing-Android) maybe
