### ISSUE TITLE
Can't create channel (iOS 13.3.1 iPad Pro: 11 inch)

### ISSUE THREAD

**Issue by Apiphoom** [AgoraIO/Advanced-Video#181]
When I test the code I only can share the screen.but I can't create a new channel
It don't have any option to enter channel name ):
![IMG_2301](https://user-images.githubusercontent.com/48949523/82868166-5f1d9700-9f56-11ea-9442-062660d4bc47.PNG)

![IMG_2300](https://user-images.githubusercontent.com/48949523/82868152-59c04c80-9f56-11ea-9975-1eb9dfa1560b.PNG)

**Comment by Apiphoom** [comment]
@plutoless Please help ):

**Comment by Apiphoom** [comment]
Already fix with app group and new Api framework

**Comment by plutoless** [comment]
good to know it works. sorry for late reply

**Comment by Apiphoom** [comment]
never mind now it all work perfectly (:

**Comment by saimt** [comment]
Hi I am facing this issue again. iphone 11, ios 13.5.1. Can you check?
