### ISSUE TITLE
windows AgoraMediaSource非DirectX版本和directX版本的问题

### ISSUE THREAD

**Issue by liuzhan214** [AgoraIO/Advanced-Video#183]
windows AgoraMediaSource非DirectX版本无法联网，directX版本编译无法通过

**Comment by sbd021** [comment]
都是dx版本，dx 2010需要安装2010 june版本，配合vs2013。
另外一个是用新版本的dx，不需要安装，win8以上系统自带。不能联网可能没申请appid。可以参考一下readme，有相关说明。
