### ISSUE TITLE
Android - (Raw Data) onCaptureVideoFrame and onRenderVideoFrame methods don't get called with App Bundle

### ISSUE THREAD

**Issue by Apollo122** [AgoraIO/Advanced-Video#185]
Hello,

Raw data lib works when we create regular APK but it doesn't work with App Bundle. 
Neither `onCaptureVideoFrame` nor `onRenderVideoFrame` methods gets called at `MediaDataObserverPlugin.class`
How can we resolve this issue? We need the solution ASAP please

**Comment by brianxcli** [comment]
By default, Android Studio plugin packages uncompressed native libraries into app bundles. Thus the originally uncompressed native libraries in path/to/app/lib will be missing. 

"As a temporary workaround, you can also use 
android.bundle.enableUncompressedNativeLibs=false
in your gradle.properties until we address this more permanently."

https://issuetracker.google.com/issues/127691101

Please take a look at this post.
