### ISSUE TITLE
Add effect for video call

### ISSUE THREAD

**Issue by phuongvnc** [AgoraIO/Advanced-Video#187]
I am developing an effect for video calls. I already use a sample raw data API for our app. But I have an issue about converting CGPixelBuffer to AgoraVideoRawData. Could you suggest to me about it or send to me some code convert it?

**Comment by phuongvnc** [comment]
Plz help me

**Comment by yoreland** [comment]
Hi, do you mean CVPixelBuffer for iOS platform?

If so below document link should help you:
https://docs.agora.io/en/Video/raw_data_video_apple?platform=iOS#示例代码

**Comment by phuongvnc** [comment]
> Hi, do you mean CVPixelBuffer for iOS platform?
> 
> If so below document link should help you:
> [https://docs.agora.io/en/Video/raw_data_video_apple?platform=iOS#示例代码](https://docs.agora.io/en/Video/raw_data_video_apple?platform=iOS#%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81)

I already read it. But I don't know how to convert CVPixelBuffer to VideoFrame. If you have a demo for it. Plz send to me or suggest your solution for me

**Comment by plutoless** [comment]
hi @phuongvnc you can in fact take [this](https://github.com/AgoraIO/Advanced-Video/blob/f96c77ae32670a7f3c00680bf6b1e38207db5493/iOS%26macOS/Agora-Plugin-Raw-Data-API-Objective-C/raw-data-api-oc/AgoraMediaDataPlugin.mm#L488) as a guidance code. it's not doing exactly what you need but has shown you the basic idea.

you will need to use CVPixelBufferGetBaseAddressOfPlane to get base address of y/u/v planar, and then use memcpy to copy yuv data into AgoraVideoRawData, AgoraVideoRawData is just a wrapper of yuv data and all you need to do is to overwrite the data with the one you changed in CVPixelBuffer.

**Comment by truonglocbinh** [comment]
@phuongvnc sorry but maybe my question not relevant with your question, but I do same task about customize raw video data from agora and I see my phone to be hot faster . Do you try it on iphone, and how do you see about temperature of your phone before and after use your feature ?

**Comment by tomosia-phuongvo** [comment]
@truonglocbinh We used the BanubaSDK effect for Agora Video Call. You could download the demo and try to apply it to your project. My device is warm when using it longer
https://github.com/AgoraIO-Solutions/BNBEffectPlayer-Agora
