### ISSUE TITLE
ShareScreen volume problem (Swift5) iOS

### ISSUE THREAD

**Issue by Apiphoom** [AgoraIO/Advanced-Video#192]
when I share my screen I open YouTube everything work very good! except microphone sound(from another speaker) is very very low
(or I think YouTube sound is very loud)

how I gonna fix this Pls help
I use swift5

**Comment by Apiphoom** [comment]
@plutoless Pls help you are my only hope ;-;

**Comment by yoreland** [comment]
Hi, the screen share demo is just using apple's replayKit to capture screen and mixing app&mic audio. 
From our side, seems the issue is un-reproducible. Did you try to play movie from other app or using different device to avoid mic issues?

**Comment by Apiphoom** [comment]
Yeah now I fix it with separate audio and video😂

**Comment by Apiphoom** [comment]
@yoreland can you close this issue? (; I already fix this problem now.
