### ISSUE TITLE
Broadcast not starting (iOS)

### ISSUE THREAD

**Issue by saimt** [AgoraIO/Advanced-Video#196]
I am using iPhone 11 iOS version is 13.5.1
When I try to broadcast, RPSystemBroadcastPickerView is displayed, on tapping 'Start Recording' it doesn't ask for channel name or anything. 
I think it's the same issue like #181 . Something related to OS version

**Comment by Apiphoom** [comment]
Are you still have a problem?

**Comment by Apiphoom** [comment]
If you want to broadcast you need to use app group for send channel name from main program to extension

**Comment by Apiphoom** [comment]
`class SampleHandler: RPBroadcastSampleHandler {
    
    var sendAudioChecker = true
    
    override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
        
        
        let defaults = UserDefaults(suiteName: "group.com.blablabla.Api")
        let IDS = defaults?.string(forKey: "API")
        
        
        if let setupInfo = setupInfo, let channel = setupInfo["channelName"] as? String {
            //In-App Screen Capture
            AgoraUploader.startBroadcast(to: channel)
        } else {
            //iOS Screen Record and Broadcast
            print(IDS!)
            print("start broadcast")
        AgoraUploader.startBroadcast(to:IDS!)
        }
    }`

**Comment by saimt** [comment]
Hi thank you for reply.
`override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) { }` 
If I'm not wrong this function is automatically triggered when user taps on start recording, but in my case this function is not triggering. I've added breakpoints in it but it never gets called

**Comment by Apiphoom** [comment]
when I try the sample code it not work too I use app group and start broadcast by use `  if #available(iOS 12.0, *) {
                              let broadcastPicker = RPSystemBroadcastPickerView(frame: CGRect(x: 5, y: 5, width: 40, height: 40))
                               broadcastPicker.preferredExtension = "com.blablabla.Broadcast"
                           
                              ShareScreen.addSubview(broadcastPicker)
                           
                           
                           
                           
                              
                          } else {
                              // Fallback on earlier versions
                          }`

and then use app group to transfer channel name to broadcast extension and start broadcast by 
`override func broadcastStarted(withSetupInfo setupInfo: [String : NSObject]?) {
    
    
    let defaults = UserDefaults(suiteName: "group.com.blablabla.Api")
    let IDS = defaults?.string(forKey: "API")
    
    
    if let setupInfo = setupInfo, let channel = setupInfo["channelName"] as? String {
        //In-App Screen Capture
        AgoraUploader.startBroadcast(to: channel)
    } else {
        //iOS Screen Record and Broadcast
        print(IDS!)
        print("start broadcast")
    AgoraUploader.startBroadcast(to:IDS!)
    }
}`

**Comment by saimt** [comment]
Ok. Let me give it a try

**Comment by Apiphoom** [comment]
Ok 👍

**Comment by saimt** [comment]
I've tried following things:

1. In _viewDidLoad_ of **BroadcastViewController** I added:

`
let userDefaults = UserDefaults(suiteName: "group.com.agora.ios")!
userDefaults.set("12345", forKey: "API") 
userDefaults.synchronize()
`

2. In _broadcastStarted_ of **SampleHandler** I added:

`
let defaults = UserDefaults(suiteName: "group.com.agora.ios")
        let IDS = defaults?.string(forKey: "API")
        print(IDS!)
        if let setupInfo = setupInfo, let channel = setupInfo["channelName"] as? String {
            //In-App Screen Capture
            AgoraUploader.startBroadcast(to: channel)
        } else {
            //iOS Screen Record and Broadcast
            print(IDS!)
            print("start broadcast")
            AgoraUploader.startBroadcast(to:IDS!)
        }
`

but it's still the same. in this case channel name is **12345** and I tried to view the livestream with this channel name but there was nothing. 
Tell me if I'm doing something wrong

**Comment by plutoless** [comment]
have you turned on token feature in your agora dashboard?

**Comment by saimt** [comment]
Yes I have.

**Comment by saimt** [comment]
So in ### agoraEngine.JoinChannel token was set to nil, I changed it to the token from KeyCenter but still nothing. 

Maybe it has started uploading the broadcast, but in **AudienceViewController** VideoSession is nil

**Comment by plutoless** [comment]
maybe you can try creating a new project w/o token and see if it's working for you or not? just for experiments

**Comment by saimt** [comment]
Did that. Still the same

**Comment by saimt** [comment]
Ok. Apparently creating a project without token worked. Thank you

**Comment by plutoless** [comment]
@saimt to help you understand what is happening
https://github.com/AgoraIO/Advanced-Video/blob/83674ba810c081e71214a91652a7c9eaffdd84b7/iOS%26macOS/Agora-Screen-Sharing/Agora-Screen-Sharing-iOS-Broadcast/AgoraUploader.swift#L59
you will need to provide a token here, and the channel you used to generate the token should match with the name of the channel which you are joining.

**Comment by saimt** [comment]
Hi, Yes I did that but it didn't work. Earlier on Agora dashboard, I created a project with **App ID + App Certificate + Token** which wasn't working. Now I created the project with **App ID** only. So I changed the AppID in _KeyCenter_ and it started working.

**Comment by plutoless** [comment]
if it works with an AppID only project, it can almost be certain that your issue is caused by token authentication. 
you can create a event listener and set it as sdk delegate here
https://github.com/AgoraIO/Advanced-Video/blob/83674ba810c081e71214a91652a7c9eaffdd84b7/iOS%26macOS/Agora-Screen-Sharing/Agora-Screen-Sharing-iOS-Broadcast/AgoraUploader.swift#L32

so that you can listen to onError events to check out what kind of error code you are having when joining channel.
