### ISSUE TITLE
AudioSession is switched from active to inactive a few times

### ISSUE THREAD

**Issue by Ky4a** [AgoraIO/Advanced-Video#199]
**Describe the bug**

With the latest SDK 3.0.1.1 and CallKit I'm noticing that AVAudioSession is set active then inactive and active back (I set symbolic breakpoint). There is Red Microphone appears at the status bar after a few seconds after an app joined a channel.

As I see this project doesn't have CallKit example anymore. I have the old one AgoraRTCWithCallKit and if I replace SDK to the latest one I'm getting this issue there too.

**To Reproduce**

Replace SDK for the project AgoraRTCWithCallKit
Run the project AgoraRTCWithCallKit. Click Outgoing Call. 
You notice the Red Mic icon at the status bar. The delegate method didAudioRouteChanged are called 2-3 times instead of one time. If you set a breakpoint on the method -[AVAudioSession setActive:withOptions:error:] you will see it's called a few times (instead on one time with previous SDK)

**Expected behavior**

AVAudioSession should be set active once

**Screenshots**

![IMG_1EA925431E46-1](https://user-images.githubusercontent.com/15935726/86894537-64f9c100-c12d-11ea-82d8-8a4dfb040cef.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.5

**Comment by plutoless** [comment]
i will check tomorrow
