### ISSUE TITLE
change audience role to broadcaster

### ISSUE THREAD

**Issue by saimt** [AgoraIO/Advanced-Video#202]
Hi, I have been trying to change the role of specific audience member to broadcaster. So that the screen sharing is mine but I can hear the audio of other co-host. 

I have been following this guide. [https://docs.agora.io/en/faq/host_set_role](url) 
I have converted role of audience member, but main broadcaster is not able to hear the audio of co-host. I'm not sure if co-host's audio is streaming, or maybe it's streaming but main broadcaster is not receiving it. 

On audience side after converting the role I did:
```
rtcEngine.setClientRole(.broadcaster)
rtcEngine.enableLocalAudio(true)
rtcEngine.muteLocalAudioStream(false)
```

An on Broadcaster Side I have enabled remote audios
```
kit.setDefaultAudioRouteToSpeakerphone(true)
kit.enableAudio()
kit.muteAllRemoteAudioStreams(false)
```

Any help would be appreciated

**Comment by brianxcli** [comment]
Which platform are you using?

**Comment by saimt** [comment]
I’m using iOS

**Comment by saimt** [comment]
Is there any way possible that 2 broadcasters can hear each other? Right now broadcaster can't hear anyone else

**Comment by plutoless** [comment]
can your audience hear broadcaster?

**Comment by saimt** [comment]
yes audience can hear a broadcaster. What I want to achieve is that if there are 2 broadcasters, they can hear each other.

**Comment by plutoless** [comment]
if audience can hear broadcaster, then broadcaster should be able to hear each other, could you pls help reproduce the issue and share the channel name + timestamp when the issue happened for me to investigate?

**Comment by saimt** [comment]
I did some research and figured out that broadcast extensions only support streaming and not receiving, so even if you 
do this `kit.muteAllRemoteAudioStreams(false)` in AgoraUploader you still won't be able to receive streams from others (whether audience or another broadcaster).

Correct me if I'm wrong.

**Comment by plutoless** [comment]
@saimt why do you want to hear others from extension? does it work if you do this in your main process?

**Comment by saimt** [comment]
I tried doing it from the main process. I did the following things:

1. Created a new instance of RTCEngine (couldn't figure out any way to access the instance running in broadcast extension. if there is any way please tell me.)
2. Joined the same channel (on which I am broadcasting) as a broadcaster. 

This didn't work. Is there any way this can be done?

**Comment by plutoless** [comment]
main process can't access variables in extension. Could you pls share me the channel name you used, so that i can take a look from backend?

**Comment by plutoless** [comment]
maybe it's worth to start with this tutorial first?
https://github.com/AgoraIO/Basic-Video-Call/tree/master/One-to-One-Video/Agora-iOS-Tutorial-Swift-1to1

**Comment by saimt** [comment]
Hi, I used the channel name "qwe" for broadcast testing. I have tried the link you shared. It works fine with multiple broadcasters, but this is for video sharing. I want to do the same thing with screen sharing.

**Comment by plutoless** [comment]
let me double verify, currently the issue is you have one process joining channel in main process, and the other one joining channel in extension. Both are broadcasters and they can't hear each other, right?

**Comment by saimt** [comment]
Broadcaster joining with main process can hear the other broadcaster who has joined with extension. But the broadcaster who joined with extension cannot hear other broadcaster who joined with the main process.
