### ISSUE TITLE
使用Agora-Media-Source-Windows工程,点击扩展采集会退出

### ISSUE THREAD

**Issue by l252** [AgoraIO/Advanced-Video#206]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by l252** [comment]
![image](https://user-images.githubusercontent.com/68628532/88146034-ecffc080-cc2d-11ea-8210-6b0fc958bf29.png)

**Comment by Apiphoom** [comment]
Ahhh can you comment this issue again in English?

**Comment by l252** [comment]
Using the Agora-Media-Source-Windows project, click on extended Acquisition to exit,See the picture above

**Comment by CLuCheng** [comment]
You can check the return value of the ptrCreateDevEnum->CreateClassEnumerator.
The bug might have been caused by a failed call to CreateClassEnumerator.
