### ISSUE TITLE
Share-Screen error (SDK 3.1.0)

### ISSUE THREAD

**Issue by Apiphoom** [AgoraIO/Advanced-Video#210]
when I share-screen it can only share for 15 sec (every time) and it turn to grey screen. How can I solve this problem or it's a SDK bugs? @plutoless @PRWrl @guohai PLS help

**Comment by yoreland** [comment]
What's your platform? Can you share related logs for that?

**Comment by Apiphoom** [comment]
Sure! I am on iOS platform It doesn't show any error except it can only share-screen for 15 sec (every time) and it turn to grey screen

**Comment by Apiphoom** [comment]
I think it a SDK 3.0.0.1 bugs😢😭

**Comment by CavanSu** [comment]
What's your os version and device？ @Apiphoom

**Comment by Apiphoom** [comment]
@CavanSu iPad pro 11 inch / iPad Gen 7 / iPad Pro 10.5 inch / iPad Gen 5 all of it is iOS 13.5

**Comment by Apiphoom** [comment]
@CavanSu the last SDK (3.1.0) also have this problem too (I try already try it in iOS 13.6 / 13.5 / 14)

**Comment by CavanSu** [comment]
@Apiphoom crash reason is 50 limit? we already know a problem that if the microphone button is turned off before the screen recording, and then start recording, turn on the microphone button during the recording process, the memory will increase above 50M and be killed by the system on ios 13. this problem is cause by apple, you can try to comment out all our code.

**Comment by Apiphoom** [comment]
@CavanSu My Application didn’t crash but when I use SDK 3.1.0 or 3.0.1.1
I can only share my screen for 15 sec and audience view will change to gray
screen but audience can hear audio but can’t receive any video (It turn to gray screen) This bugs not happens in SDK 3.0.0.2

**Comment by CavanSu** [comment]
I try to reproduce, but I didn't reproduce this bug. can you upload broadcaster and audience rtc sdk log?  if you can record a video to tell me how to repruduce this bug, I should be able to fix this problem faster @Apiphoom

**Comment by Apiphoom** [comment]
@CavanSu Ok I will send video as soon as possible
