### ISSUE TITLE
Questions on sample projects - Android

### ISSUE THREAD

**Issue by ArcherEmiya05** [AgoraIO/Advanced-Video#212]
Good day, the sample apps and SDK itself are still awesome and robust. Great work!

I just have some few question on one of the sample particularly in **PacketProcessor.class** that uses native library written in C++.

1. How can I check if `packet_processing_plugin_jni` is working properly and what exactly it is, like where it is source and does it have any documetation?

2. Can we use it as well in voice call project sample?

Another one is that I cannot see a working sample with **share screen** as it is seems to be included in **README.md** file in this Advance Video project.

**Comment by plutoless** [comment]
hi @ArcherEmiya05 the corresponding c++ files are placed here
https://github.com/AgoraIO/Advanced-Video/tree/f96c77ae32670a7f3c00680bf6b1e38207db5493/Android/sample-video-encrypt/src/main/cpp
packet_processing_plugin_jni is basically a c++ jni wrapper for you to call c++ apis from java.

And you can for sure use in the voice call project.

For share screen please look at switch external video sample

**Comment by ArcherEmiya05** [comment]
Is there a way to know if it works properly, sorry not familiar with native C++ thing :<

**Comment by plutoless** [comment]
what feature do you want to achieve?

**Comment by ArcherEmiya05** [comment]
Just wanted to log any details or related from encrypted packet data while having a call session.
