### ISSUE TITLE
Sample Android CRASH 

### ISSUE THREAD

**Issue by vaibhav2800** [AgoraIO/Advanced-Video#215]
I am using Advance Video sample for Push Video and it is getting crash on Android with following error logs.

Build fingerprint: 'xiaomi/mido/mido:7.0/NRD90M/V10.2.3.0.NCFMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 13702, tid: 13702, name: video.videopush  >>> io.agora.advancedvideo.videopush <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    x0   0000000000000000  x1   0000000000003586  x2   0000000000000006  x3   0000000000000008
    x4   0000007f5b1ff100  x5   0000007ff5d27840  x6   0000007f800aa000  x7   0000000000000000
    x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  ffffffffa0d2972f  x14  0016bf623f000000  x15  003b9aca00000000
    x16  0000007f7ea54ed0  x17  0000007f7e9fe510  x18  0000000000015180  x19  0000007f8015eb48
    x20  0000000000000006  x21  0000007f8015eaa0  x22  000000000000000b  x23  0000007f5c980680
    x24  0000007f5cd70b80  x25  0000000000055730  x26  00000000000003e8  x27  0000007f5c9806bc
    x28  0000000000000000  x29  0000007ff5d278b0  x30  0000007f7e9fb9a0
    sp   0000007ff5d27890  pc   0000007f7e9fe518  pstate 0000000060000000

backtrace:
    #00 pc 000000000006b518  /system/lib64/libc.so (tgkill+8)
    #01 pc 000000000006899c  /system/lib64/libc.so (pthread_kill+64)
    #02 pc 0000000000023ee8  /system/lib64/libc.so (raise+24)
    #03 pc 000000000001c96c  /system/lib64/libc.so (abort+52)
    #04 pc 00000000007e4e44  /data/app/io.agora.advancedvideo.videopush-1/lib/arm64/libagora-rtc-sdk.so

1. Download sample for Advance video
2. Open in android studio
3. Select "Sample Push Video"
4. create a broadcaster and once done it will open camera screen for 1 second and crashes after that.

I have tried it on 3 different Android devices and different OS version as well. I am using master branch sample .

**Smartphone (please complete the following information):**
 - Device: Xiaomi note 5 , Readmi note , MediaTek chipset 
 - OS: Android

**Comment by plutoless** [comment]
how do you integrate our sdk? via gradle?

**Comment by vaibhav2800** [comment]
Sorry about so late response . This issue was address by Agora support team when I reached to them via support portal . As that version was having issues so updating the sdk version helped in this . 
Thanks
