### ISSUE TITLE
int cannot be dereferenced

### ISSUE THREAD

**Issue by klionsome** [AgoraIO/Advanced-Video#220]
During compilation Screen Share it shows this error:

C:\code\screenshar\screensharing\src\main\java\io\agora\rtc\ss\ScreenSharingClient.java:86: 

error: int cannot be dereferenced
            intent.putExtra(Constant.FRAME_RATE, vec.frameRate.getValue());
                                                              ^

**Comment by plutoless** [comment]
how did you define intent? looks like you are trying to migrate the code into your own project and something went wrong? i tried our own demo and it's working fine.
