### ISSUE TITLE
enableLocalVideo | muteLocalVideoStream not working

### ISSUE THREAD

**Issue by ArcherEmiya05** [AgoraIO/Advanced-Video#221]
This is weird, before when I am using `enableVideo()` it seems to work fine but due to special case I need to change it and when I tried to call `enableLocalVideo(true)` followed by `muteLocalVideoStream(false)` all before joining the channel, the camera on local video never turns on. I am using `io.agora.rtc:full-sdk:3.1.0` and also tried `io.agora.rtc:full-sdk:3.1.1` both not working fine.
I am using Xiaomi Mi 9T Pro Android 10.

Expected behaviour : Calling `enableLocalVideo(true)` alone should at least open my camera but nothing happens.

**Comment by plutoless** [comment]
if you want to start camera before join channel, you will need to call startPreview
