### ISSUE TITLE
Encypt demo doesn't work(加密demo不正常)

### ISSUE THREAD

**Issue by luozejiaqun** [AgoraIO/Advanced-Video#239]
I run the sample-video-encrypt demo, and find that the encryption method doesn't work properly. 
https://github.com/AgoraIO/Advanced-Video/blob/master/Android/sample-video-encrypt/src/main/cpp/packet_processing_plugin_jni.cpp#L121
The register method work properly(log has printed).
https://github.com/AgoraIO/Advanced-Video/blob/master/Android/sample-video-encrypt/src/main/cpp/packet_processing_plugin_jni.cpp#L50
and
https://github.com/AgoraIO/Advanced-Video/blob/master/Android/sample-video-encrypt/src/main/cpp/packet_processing_plugin_jni.cpp#L65
But the real encrypt method has not been invoked(log doesn't print).
So what's the problem?
运行sample-video-encrypt demo发现注册方法成功调用（日志正常输出），但是实际加解密方法未被调用（日志未输出），这是什么情况？

**Comment by plutoless** [comment]
@luozejiaqun 这个仓库接下去会被归档，请参考
https://github.com/AgoraIO/API-Examples 中的自定义加解密示例
