### ISSUE TITLE
AgoraMeeting problem

### ISSUE THREAD

**Issue by Apiphoom** [AgoraIO/Advanced-Video#243]
I have some problem in AgoraMeeting can you please help me solve the issue? Thank you very much
(You can see the issue in https://github.com/AgoraIO-Usecase/AgoraMeeting/issues/8)

@yoreland 
@plutoless

**Comment by yoreland** [comment]
Agora Video Call isn't open source software.
If you are just interested in a sample for integrated RTM and RTC sdk together for a live meeting scenario. You might be interested in this demo:
https://github.com/AgoraIO-Usecase/AgoraMeeting

**Comment by Apiphoom** [comment]
Thank! But I have some problem in AgoraMeeting can you please help me solve me the issue? Thank you very much
(You can see the issue in https://github.com/AgoraIO-Usecase/AgoraMeeting)

@yoreland
