### ISSUE TITLE
Openlive  project integration

### ISSUE THREAD

**Issue by plutomen** [AgoraIO/Advanced-Video#27]
Hey i have integrated the project Openlive for ARcore but having some issue. it says missing class VideoEncoderConfiguration. can you please help on that !
 thank you

**Comment by plutoless** [comment]
@plutomen  this is a new class introduced after 2.3.2. Could you pls check your SDK version? Cheers.

**Comment by plutomen** [comment]
ok. Thank you for the help that worked. i was not aware about the updated (2.3.2) version!...
