### ISSUE TITLE
[Bug] screenshare app is not working on android. 

### ISSUE THREAD

**Issue by ishaang10** [AgoraIO/Advanced-Video#30]
I tried to work the screenshare appp sample for android but got black screen on the web chanel. please fix this

**Comment by ishaang10** [comment]
solved . ..!! just add enableWebSDKinterportablitity method and it works

**Comment by karan1213** [comment]
Hello, I can't make the demo app work. I added `enableWebSDKinterportablitity` method also.
Any help?

**Comment by ishaang10** [comment]
Can you tell me two things...
1. how did you use the method(what parameters did you pass)
2. please share the error log




whats the problem? black screen?

**Comment by karan1213** [comment]
ishaang10, It's used Gradle dependency instead of Jar file and worked fine, but it was not working with Jar file as mentioned in the Docs.
