### ISSUE TITLE
Resolution and quality in android compared to ios

### ISSUE THREAD

**Issue by ishaang10** [AgoraIO/Advanced-Video#31]
I tried the screensharing in android and my friend did the same in ios. but the resolution in android is far worse than ios . how can i improve that . both of them are doing the same thing .

**Comment by guohai** [comment]
Thanks. we will make the screen sharing video resolution larger. But for now, if you want to make it work right now, just change setVideoProfile to VIDEO_PROFILE_720P.

**Comment by ishaang10** [comment]
i solved it the other way. the method was depricated so i used your modified method. thanks
