### ISSUE TITLE
BUG- iOS Data stream not working both side

### ISSUE THREAD

**Issue by PrashantKT** [AgoraIO/Advanced-Video#34]
I am facing issue.

I am trying to create a data stream to pass string as Data between two persons.

**Audience (not working)**

  `  var dataStreamID:Int = -1`

Here how I setup Agora 

 ```
  func loadAgoraKit() {
        rtcEngine = AgoraRtcEngineKit.sharedEngine(withAppId: KeyCenter.AppId, delegate: self)
        rtcEngine.setChannelProfile(.liveBroadcasting)
        rtcEngine.enableVideo()
        rtcEngine.enableDualStreamMode(true)
        
        rtcEngine.setClientRole(.audience)
        rtcEngine.setDefaultAudioRouteToSpeakerphone(true)
        
        let code = rtcEngine.joinChannel(byToken: nil, channelId: channelName, info: nil, uid: 0, joinSuccess: nil)
        if code != 0 {
            DispatchQueue.main.async(execute: {
                self.alert(string: "Join channel failed: \(code)")
            })
        }
        
        
        
        rtcEngine.createDataStream(&dataStreamID, reliable: true, ordered: true)
        rtcEngine.setEnableSpeakerphone(true)

        
    }

On some  Screen tapped  I am sending text 

  
    let success = rtcEngine.sendStreamMessage(dataStreamID, data: "Double Tapped".data(using: .utf8)!)
        print(success) // This is 0 
```
 
I have checked  **success** is 0 

After some time this method calls

 ```
   func rtcEngine(_ engine: AgoraRtcEngineKit, didOccurStreamMessageErrorFromUid uid: UInt, streamId: Int, error: Int, missed: Int, cached: Int) {
        print(#function)
    }

```

**With Error Code 117** 

**Boradcaster (Working)**

In broadcaster I have following code. 

```
 static let sharedAgoraEngine: AgoraRtcEngineKit = {
        let kit = AgoraRtcEngineKit.sharedEngine(withAppId: KeyCenter.AppId, delegate: delegateHandler)
        kit.setChannelProfile(.liveBroadcasting)
        kit.setClientRole(.broadcaster)
        
        kit.enableVideo()
        kit.setVideoSource(videoSource)
        kit.enableDualStreamMode(true)
        kit.setDefaultAudioRouteToSpeakerphone(true)

      //  kit.setExternalVideoSource(true, useTexture: true, pushMode: true)
        let videoConfig = AgoraVideoEncoderConfiguration(size: videoDimension,
                                                         frameRate: .fps24,
                                                         bitrate: AgoraVideoBitrateStandard,
                                                         orientationMode: .adaptative)
        kit.setVideoEncoderConfiguration(videoConfig)
        
     //   AgoraAudioProcessing.registerAudioPreprocessing(kit)
      //  kit.setRecordingAudioFrameParametersWithSampleRate(44100, channel: 1, mode: .readWrite, samplesPerCall: 1024)
     //   kit.setParameters("{\"che.audio.external_device\":true}")

        
        kit.enableAudio()
      
//        kit.muteAllRemoteVideoStreams(true)
//        kit.muteAllRemoteAudioStreams(true)
        
        return kit
    }()
    
    static func startBroadcast(to channel: String) {
             
        let code =  sharedAgoraEngine.joinChannel(byToken: nil, channelId: channel, info: nil, uid: 0) { (string, intvalue, intValue2) in
            print("Test")
            print(intvalue)
        }

        
        print(code)
        
        sharedAgoraEngine.createDataStream(&dataStreamID, reliable: true, ordered: true)
        sharedAgoraEngine.setEnableSpeakerphone(true)
       
    }
```

I am able to send the message . Broadcaster ==>  Audience but  
not Audience ==> Broadcaster 

Please help

**Comment by plutoless** [comment]
https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a204f2018c63d2291c7bfe880109e502e
The doc clearly mentioned it only works for communication profile or live broadcaster.

**Comment by PrashantKT** [comment]
@plutoless  Thank you for your response you mean  Audience role not allowed to send data using data stream so  I have to make both broadcaster ?

**Comment by plutoless** [comment]
@PrashantKT  Yes.

**Comment by PrashantKT** [comment]
@plutoless  Thanks that helps :)

**Comment by PrashantKT** [comment]
@plutoless Another question  If you could help me. Suppose User (User1) joined a channel,After some time  other user joined channel (User2). then I get delegate method called   for both  `func rtcEngine(_ engine: AgoraRtcEngineKit, didJoinedOfUid uid: UInt, elapsed: Int`

My question is is there a way to check how many user has been already in the channel when any user joined the particular channel like User1 Joined  there was no one in channel. But when User2 Joined there is one user (User1) is in the channel.

**Comment by plutoless** [comment]
@PrashantKT  for the first time you joined channel, the callback will be called for users who are already in channel as well.

**Comment by PrashantKT** [comment]
@plutoless  Thanks for comment. I am already aware of it. What I am asking is How can I get the list of users in particular  channel any time. for example channel is empty and when user1 joined channel I need to know that channel is empty when user1 is joined in this case there is no call back called. hope you are getting my point

**Comment by plutoless** [comment]
you can set up a timer to confirm if there’s any callbacks or not.
Or you can use our restful api to get user list while you are not in the channel. But note this api is for your administration purpose and cannot be called to frequently, meaning it may not be that appropriate to call it from your client.
Hope this answers your question.

**Comment by karan1213** [comment]
> @plutoless Thanks that helps :)

Does making both 'Broadcaster' worked for you? For me, it didn't. I am trying with Android SDK

**Comment by plutoless** [comment]
@karan1213  any more details for how it's not working?

**Comment by karan1213** [comment]
I kept everything as it is except the `mRtcEngine.setClientRole(Constants.CLIENT_ROLE_BROADCASTER);`
I made both Broadcaster & Audience `Broadcaster` as mentioned above but still couldn't receive data stream messages at the broadcaster end.

Also, I'm thinking of why there is such a restriction applied. I mean what if an audience member wants to send/notify of something like sending an emojis while streaming his screen share, How we should implement this is data stream messages from Audience to Broadcaster is not allowed/recommended?

**Comment by plutoless** [comment]
which channel profile are you using? Have you called setChannelProfile to set the profile to livebroadcasting

**Comment by karan1213** [comment]
Yes, the channel profile is set to livebroadcasting.

**Comment by plutoless** [comment]
can you see each other's video in the channel?
It's recommended to use extra signaling lib if you want to send/receive messages

**Comment by karan1213** [comment]
Yes, I can see video but no stream messages.

**Comment by plutoless** [comment]
any chance you can provide your project or sdk logs so that i can take a look in detail?

**Comment by PrashantKT** [comment]
@plutoless  I am facing issue to install application in iPhone 6s and app is crashing on launch with

Following error 

dyld: Symbol not found: _OBJC_CLASS_$__TtCs12_SwiftObject
  Referenced from: /var/containers/Bundle/Application/AAC7621A-5712-4557-A187-4E940276EFDD/AgoraARKit.app/AgoraARKit
  Expected in: /usr/lib/swift/libswiftCore.dylib
 in /var/containers/Bundle/Application/AAC7621A-5712-4557-A187-4E940276EFDD/AgoraARKit.app/AgoraARKit


Please help

**Comment by karan1213** [comment]
> any chance you can provide your project or sdk logs so that i can take a look in detail?
**AudienceActivity.Java**
`private void initEngineAndJoin() {
        try {
            mRtcEngine = RtcEngine.create(getApplicationContext(), getString(R.string.agora_app_id), new IRtcEngineEventHandler() {

                @Override
                public void onJoinChannelSuccess(String channel, int uid, int elapsed) {
                    Log.d(TAG, "onJoinChannelSuccess: " + (uid&0xFFFFFFL));
                }

                @Override
                public void onUserJoined(final int uid, int elapsed) {
                    Log.d(TAG, "onUserJoined: " + (uid&0xFFFFFFL));
                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            setupRemoteView(uid);
                        }
                    });
                }

                @Override
                public void onStreamMessage(int uid, int streamId, byte[] data) {
                    super.onStreamMessage(uid, streamId, data);
                }

                @Override
                public void onStreamMessageError(int uid, int streamId, int error, int missed, int cached) {
                    Log.d(TAG, "onStreamMessageError: " + uid + " " + streamId + " " + error);
                    super.onStreamMessageError(uid, streamId, error, missed, cached);
                }

            });
        } catch (Exception e) {
            e.printStackTrace();
        }
        mRtcEngine.enableWebSdkInteroperability(true);
        mRtcEngine.setChannelProfile(Constants.CHANNEL_PROFILE_LIVE_BROADCASTING);
        mRtcEngine.enableVideo();
        mRtcEngine.setClientRole(Constants.CLIENT_ROLE_BROADCASTER);

        mRtcEngine.joinChannel(null, "ss_test2", "", 0);
        dataStream = mRtcEngine.createDataStream(true, true);

    }`

**HelloAgoraScreenSharingActivity**
`private void initModules() {
        DisplayMetrics metrics = new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(metrics);

        -------------------------------------------

mRtcEngine.enableWebSdkInteroperability(true);
            mRtcEngine.setChannelProfile(Constants.CHANNEL_PROFILE_LIVE_BROADCASTING);
            mRtcEngine.enableVideo();
            mRtcEngine.addHandler(new IRtcEngineEventHandler() {
                @Override
                public void onStreamMessage(int uid, int streamId, byte[] data) {
                    Log.d(LOG_TAG, "onStreamMessage: " + uid + " " + streamId + " " + data);
                    super.onStreamMessage(uid, streamId, data);
                }

                @Override
                public void onStreamMessageError(int uid, int streamId, int error, int missed, int cached) {
                    Log.d(LOG_TAG, "onStreamMessageError: " + uid + " " + streamId + " " + error);
                    super.onStreamMessageError(uid, streamId, error, missed, cached);
                }
            });
            if (mRtcEngine.isTextureEncodeSupported()) {
                mRtcEngine.setExternalVideoSource(true, true, true);
            } else {
                throw new RuntimeException("Can not work on device do not supporting texture" + mRtcEngine.isTextureEncodeSupported());
            }

            mRtcEngine.setVideoProfile(Constants.VIDEO_PROFILE_360P, true);

            mRtcEngine.setClientRole(Constants.CLIENT_ROLE_BROADCASTER);`

Rest code is as it is.

**Comment by plutoless** [comment]
@karan1213  you need to wait for onJoinChannelSuccess callback to perform other following tasks. JoinChannel is an asynchronous operation so you cannot just start creating datastream channel right after that.

**Comment by karan1213** [comment]
@plutoless 
Tried, but still not working.
Stream messages are transferred from both receiver and sender end but received only at the receiver end.

**Comment by plutoless** [comment]
@karan1213 what if you wait till onUserJoined callback is called for the other user? i.e. try to createstream and send message after you successfully received opponent's video

**Comment by karan1213** [comment]
@plutoless tried, but no luck :(

**Comment by plutoless** [comment]
@karan1213 i just tried with my demo and it's working perfectly. could you pls upload your updated code? btw i just found that you are not calling sendStreamMessage, maybe show me that piece of code as well.
