### ISSUE TITLE
application sharing

### ISSUE THREAD

**Issue by plutomen** [AgoraIO/Advanced-Video#35]
when i put app in background i am also able to share my mobile screen and other applications as well ; what can i do so that i can only share agora  application view . not the whole mobile

**Comment by plutoless** [comment]
Why would you want sth like that? May i know your business requirements?

**Comment by plutomen** [comment]
With Screen sharing demo I am able to share the screen of the application which is good for us. But when the user put an application in the background. Using home button screen sharing is still continuing so other users also able to see everything on sharing device Which should not happen as per our end requirements. Could you please guide me to get rid of it.

**Comment by minmingqi** [comment]
> With Screen sharing demo I am able to share the screen of the application which is good for us. But when the user put an application in the background. Using home button screen sharing is still continuing so other users also able to see everything on sharing device Which should not happen as per our end requirements. Could you please guide me to get rid of it.

per my understanding, you may acheive your requirement by stop the screen sharing in your onStop() method in your application
