### ISSUE TITLE
Android - send custom video Buffer using Video Source 

### ISSUE THREAD

**Issue by PrashantKT** [AgoraIO/Advanced-Video#36]
I am trying to send custom byte buffer using Custom Video Source.

I have tried following 

```
agoraVideoSource.mConsumer.consumeByteBufferFrame(buffer, AgoraVideoFrame.BUFFER_TYPE_BUFFER,
                                           mSurfaceView.getWidth(), mSurfaceView.getHeight(), 0, mFrame.getTimestamp());
```

I am creating Bitmap from **PixelCopy**. 

Please HELP !! 

Here is the output. 

![Screen Shot 2019-04-17 at 1 07 17 PM](https://user-images.githubusercontent.com/35359315/56269672-d0630780-6111-11e9-85cd-dc64b9800cf4.png)

**Comment by plutoless** [comment]
What do you expect to see? Also could you pls help paste more detailed code snippet so i can understand where the raw data come from? It's hard to help with this one line code

**Comment by PrashantKT** [comment]
**What do you expect to see?**  ==> We want exact image send by broadcaster as bytebuffer. as you see it is not  showing it correctly 

**What I have done** 
My end goal is to take screenshot of screen -> Convert it to Bitmap -> Convert it to byte buffer  --> Send it with consumeByteBufferFrame method.

Here is my code to convert screen shot to the bytebuffer and then send.

```
inal Bitmap bitmap = Bitmap.createBitmap(450, 450,
               Bitmap.Config.ARGB_8888);
       // Create a handler thread to offload the processing of the image.
       final HandlerThread handlerThread = new HandlerThread("PixelCopier");
       handlerThread.start();
       // Make the request to copy.
       PixelCopy.request(mSurfaceView, bitmap, (copyResult) -> {
           if (copyResult == PixelCopy.SUCCESS) {
               try {
//                    saveBitmapToDisk(bitmap, filename);
                   runOnUiThread(new Runnable(){
                       public void run() {
                           // UI code goes here
//                            setImge(bitmap);
                           if(bitmap!=null) {
                               System.out.println("_Bitmap_"+bitmap);
                               ByteBuffer buffer = ByteBuffer.allocate(bitmap.getByteCount());
                               bitmap.copyPixelsToBuffer(buffer);
                              /* ByteArrayOutputStream stream = new ByteArrayOutputStream();
                               bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream);
                               byte[] byteArray = stream.toByteArray();
                               bitmap.recycle();*/

                               if(agoraVideoSource.mConsumer!=null) {
                                   agoraVideoSource.mConsumer.consumeByteBufferFrame(buffer, AgoraVideoFrame.BUFFER_TYPE_BUFFER,
                                           mSurfaceView.getWidth(), mSurfaceView.getHeight(), 0, mFrame.getTimestamp());
                               }
```

**Comment by plutoless** [comment]
do you mind providing your project files so that i can do a quick debug?

**Comment by plutoless** [comment]
do you mind providing your project files so that i can do a quick debug?

**Comment by PrashantKT** [comment]
@plutoless  I have created sample project.  Please check this https://github.com/dixit111/Gitshare

**Comment by CharlesLee-Ice** [comment]
@PrashantKT  I have read your sample. Found demo's problem. 
Check this out:
1. update agora sdk to latest version.
2. invoke api `consumeByteBufferFrame` with correct parameters, see details in attachment.

[java.zip](https://github.com/AgoraIO/Advanced-Video/files/3093906/java.zip)

**Comment by PrashantKT** [comment]
@CharlesLee-Ice  Thanks It works for now, I am able to see exact video frame sent by broadcaster.
But it is very slow . I have tested on high speed internet connection still  It is not smooth like iOS. it would be appreciated if you give any suggestion or sample code that may help to resolve this issue.

**Comment by PrashantKT** [comment]
@zxc524580210 Provided function working but very slow. If you see screen sharing demo, it is quite good in terms of sharing. and also iOS `consumeByteBufferFrame` is extremely fast   Please help on this.

**Comment by CharlesLee-Ice** [comment]
@PrashantKT 
Possible ways to enhance performance
1. Check [Augmented-Reality](https://github.com/AgoraIO/Advanced-Video/tree/master/Augmented-Reality/Agora-Video-With-ARCore) demo to see how it handles screen sharing;
2. Take more screen photos per second, like 30 photos per second, and also avoid costing too many time of one bitmap capturing;
3. Check `setVideoEncoderConfiguration` method and configure fps to max 30.
