### ISSUE TITLE
Its showing null point exception on Attempt to invoke virtual method 'io.agora.AgoraAPIOnlySignal com.example.interpretitnow.AGApplication.getmAgoraAPI()

### ISSUE THREAD

**Issue by jithu12** [AgoraIO/Advanced-Video#59]
![Screenshot (18)](https://user-images.githubusercontent.com/38746558/60238726-00c0e200-98c9-11e9-885a-f4be3c8032a8.png)

i don't know what is the problem behind it. 😢😭😭😭 ..please i'm new to android.

**Comment by plutoless** [comment]
which demo are you working with?

**Comment by jithu12** [comment]
Agora-RTC-With-ConnectionService-Android

**Comment by jithu12** [comment]
sir..?

**Comment by jithu12** [comment]
![Capture](https://user-images.githubusercontent.com/38746558/60246645-bcd7d800-98dc-11e9-83f8-41c1090e5bb2.JPG)
 i'm using this demo

**Comment by jithu12** [comment]
😓

**Comment by jithu12** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/38746558/60249917-57d3b080-98e3-11e9-9c12-dd9d3ebee5ef.png)

this is the page where problem persist ..i made a simple video calling application for deaf persons as my project on college.. it has connected to firebase and the data are stored in firebase ... i retrieve the account phone number and subscriber phone number from firebase... the data is retrieves successfully...but the two lines making issues always

    
**private void initAgoraEngineAndJoinChannel() {
        mAgoraAPI = AGApplication.the().getmAgoraAPI();
    }**

**initAgoraEngineAndJoinChannel();**

**Comment by plutoless** [comment]
could you pls share a minimal reproducible project?

**Comment by jithu12** [comment]
sure sir.

**Comment by jithu12** [comment]
[https://drive.google.com/drive/folders/1-F95DX8Dwdzb4yFw7ugvrYEbU5dly69Q?usp=sharing](https://drive.google.com/drive/folders/1-F95DX8Dwdzb4yFw7ugvrYEbU5dly69Q?usp=sharing)

sir its all my project

**Comment by plutoless** [comment]
i cannot access it. could you pls change to upload to OneDrive or other online file services?

**Comment by jithu12** [comment]
https://1drv.ms/u/s!AnvoTok2-zvqgoJqFfCeDxJUjqHY6w?e=dUallq


sir its compressed rar file

**Comment by jithu12** [comment]
Sir.

**Comment by plutoless** [comment]
@jithu12 i can't really run your project. It has lots or error & warnings. While from your code, i can see when running line 252 of your NumberCallActivity class, some of the variable there is not initialized, can you set a breakpoint and check which variable is null?

**Comment by guohai** [comment]
Not sure if you have configured `AGApplication` in tag `application` located in your `AndroidManifest.xml`.
Looks like so

**Comment by jithu12** [comment]
@plutoless sir sure i will.. coding this is like an Anabelle movie.. such a horrific situation.

@guohai sir i will check it out.

**Comment by guohai** [comment]
No response for a long time and we already update a new version. Close this issue.
If still has problems, open a new one

**Comment by yassineberradi** [comment]
you just need to put "android:name=".sginatutorial.AGApplication"

inside AndroidManifest.xml
