### ISSUE TITLE
import io.agora.rtc.ss.ScreenShare

### ISSUE THREAD

**Issue by pateljigar7210** [AgoraIO/Advanced-Video#60]
import io.agora.rtc.ss.ScreenShare class not found

**Comment by plutoless** [comment]
i believe it's in here https://github.com/AgoraIO/Advanced-Video/blob/master/Screensharing/Agora-Screen-Sharing-Android/screensharemodule/src/main/java/io/agora/rtc/ss/ScreenShare.java
