### ISSUE TITLE
I cant find NumbercallActivity and CallActivity

### ISSUE THREAD

**Issue by cloudtenlabs** [AgoraIO/Advanced-Video#61]

**Comment by guohai** [comment]
Which sample are you with?

**Comment by rpog** [comment]
I'm having the same issue in the sample Agora-RTC-With-ConnectionService-Android.

**Comment by guohai** [comment]
We are refactoring Agora-RTC-With-ConnectionService-Android, please wait for a few days. After done, you can try with latest sample

**Comment by Aniket-Ziffytech** [comment]
I want Agora-RTC-With-ConnectionService-Android in our app. When can I expect the latest sample?

**Comment by guohai** [comment]
pr at https://github.com/AgoraIO/Advanced-Video/pull/106

**Comment by guohai** [comment]
Merged into master branch
