### ISSUE TITLE
Where can i find RTM sdk?

### ISSUE THREAD

**Issue by cloudtenlabs** [AgoraIO/Advanced-Video#62]

**Comment by Matrixbirds** [comment]
you can find [here](https://docs.agora.io/cn/Real-time-Messaging/downloads)

**Comment by snapapplabs** [comment]
The issue was coming from I am not from China.
Agora SDK download page does not show RTM SDK if I access from outside of China

**Comment by plutoless** [comment]
which platform do you need?

**Comment by opezyhick** [comment]
i whish to add to a running project of mine , but having issue with event on a null object refrences and pointing back to base activity ....

**Comment by plutoless** [comment]
@opezyhick  w/o detail project and exception i won't be able to help. pls provide more info
