### ISSUE TITLE
screen sharing via Wifi Direct

### ISSUE THREAD

**Issue by johnny-wang16** [AgoraIO/Advanced-Video#69]
I tried the screen sharing functionality with just P2P wifi connection but it does not work. I suppose the default setting only supports wifi. Which file should I look into in order to support screen sharing via WiFi Direct?

**Comment by plutoless** [comment]
@johnny-wang16 using our RTC sdk requires going through our service edge so you have to connect to internet in order to use it. Therefore wifi direct to my understanding is not supported.
