### ISSUE TITLE
 Manual screen sharing shows green screen in iOS 13.  For iOS 12  it is working fine 

### ISSUE THREAD

**Issue by PrashantKT** [AgoraIO/Advanced-Video#74]
I am sending custom buffer and other side I am receiving and showing into screen.
Everything is working fine until iOS 12.

When I have tested the same in iOS13 It shows following output

![Simulator Screen Shot - iPhone 8 - 2019-07-18 at 18 21 54](https://user-images.githubusercontent.com/35359315/61459142-b42d6b80-a989-11e9-9d55-3aa6c10787e1.png)

This is how I create Pixel buffer and send using `ARVideoSource` 

```
    func copyPixelbufferFromCGImageProvider(image: CGImage) -> CVPixelBuffer? {
        let dataProvider: CGDataProvider? = image.dataProvider
        let data: CFData? = dataProvider?.data
        let baseAddress = CFDataGetBytePtr(data!)
        
        /**
         * We own the copied CFData which will back the CVPixelBuffer, thus the data's lifetime is bound to the buffer.
         * We will use a CVPixelBufferReleaseBytesCallback callback in order to release the CFData when the buffer dies.
         **/
        let unmanagedData = Unmanaged<CFData>.passRetained(data!)
        var pixelBuffer: CVPixelBuffer? = nil
        let status = CVPixelBufferCreateWithBytes(nil,
                                                  image.width,
                                                  image.height,
                                                  kCVPixelFormatType_32BGRA,
                                                  UnsafeMutableRawPointer( mutating: baseAddress!),
                                                  image.bytesPerRow,
                                                  { releaseContext, baseAddress in
                                                    let contextData = Unmanaged<CFData>.fromOpaque(releaseContext!)
                                                    contextData.release() },
                                                  unmanagedData.toOpaque(),
                                                  nil,
                                                  &pixelBuffer)
        
        if (status != kCVReturnSuccess) {
            return nil;
        }
        
        return pixelBuffer
    }
```
    
SDK Version 2.8.0
Xcode 11 beta 4
iOS 13.0  Simulator 

Any help or suggestion ?

**Comment by CavanSu** [comment]
can you provide agora sdk log file? ios default sdk log path: Library/Caches/

**Comment by PrashantKT** [comment]
issue is in iOS 13 simulator so where can I find log file ? , is it created in simulator document directory ?

**Comment by CavanSu** [comment]
you can find log file in your mac, like this path: /Users/xxx/Library/Developer/CoreSimulator/Devices/11AD4B5F-76F8-41BF-B3A8-9C3D837E4DD9/data/Containers/Data/Application/C1D90117-5E80-40BC-A25E-509E990CFF43/Library/Caches. it is created in Library, not documents

**Comment by PrashantKT** [comment]
@CavanSu  I am uploading log file please find it
[agorasdk.log](https://github.com/AgoraIO/Advanced-Video/files/3426410/agorasdk.log)

**Comment by plutoless** [comment]
are you using simulator or real device?

**Comment by PrashantKT** [comment]
@plutoless  Yes I am testing in iOS 13 Simulator , for other OS version everything works fine even in the simulator, Could you please suggest

**Comment by PrashantKT** [comment]
@plutoless  I have tried  same  using Twilio library and it is working fine in iOS 13 also. Could you please help me out

**Comment by plutoless** [comment]
does it work in iOS 13 real device? we don't commit to support iOS simulator

**Comment by PrashantKT** [comment]
@plutoless  Actually We don't have any updated device with iOS 13 beta. So I am testing it in simulator

**Comment by plutoless** [comment]
![IMG_0053](https://user-images.githubusercontent.com/471561/61946215-8c1ab980-afd4-11e9-9eb4-b61a71809398.PNG)
![IMG_0054](https://user-images.githubusercontent.com/471561/61946216-8c1ab980-afd4-11e9-811a-bd01763b7490.PNG)
we did a quick test on ios 13 real device and it's working fine. So you shall be OK

**Comment by PrashantKT** [comment]
@plutoless  Thank you for your kind support, Just one request to you could you please test `ARVideoSource` 's  `func sendBuffer(_ buffer: CVPixelBuffer, timestamp: TimeInterval)` Method 
your arkit demo   https://github.com/AgoraIO/Advanced-Video/tree/master/Augmented-Reality/Agora-Video-With-ARKit is it working or not, So I can be sure 


Thanks in advance

**Comment by plutoless** [comment]
sry it's weekend here. i'll do the test next monday

**Comment by PrashantKT** [comment]
@plutoless  No worries , Enjoy your weekend  😋
