### ISSUE TITLE
How i get call logs and history using RESTful api 

### ISSUE THREAD

**Issue by vishalcorea** [AgoraIO/Advanced-Video#78]
I had refer the below link 
https://docs.agora.io/en/Interactive%20Broadcast/dashboard_restful_live?platform=All_Platforms&_ga=2.231203999.1242862800.1564230695-591009821.1564230695
but couldn't find api to fetch channel history with duration of particular. could you please suggest

**Comment by plutoless** [comment]
please contact sales. we have some beta testing going on for this feature but it's not yet open to public.

**Comment by PrashantKT** [comment]
@plutoless  Any update on this ? , We also required this feature to get history of call & channel participants 
Please suggest

**Comment by plutoless** [comment]
@PrashantKT i think the development is still going on. you can talk to sales for latest update.
