### ISSUE TITLE
where to find IAgoraRtcEngine2.h

### ISSUE THREAD

**Issue by yinkaisheng** [AgoraIO/Advanced-Video#87]
Advanced-Video\Capture-Raw-Video-Data\Agora-Media-Source-Windows\AgoraMediaSource\AgoraObject.h includes
 #include "../SDK/include/IAgoraRtcEngine2.h" in line 5.

but the sdk https://download.agora.io/sdk/release/Agora_Native_SDK_for_Windows(x86)_v2_9_0_FULL.zip
only has the following header files.
AgoraBase.h
IAgoraLiveEngine.h
IAgoraLivePublisher.h
IAgoraLiveSubscriber.h
IAgoraMediaEngine.h
IAgoraRtcEngine.h
IAgoraService.h

the readme.md says :
"For master branch
You need IAgoraRtcEngine2.h header file."
Where to find IAgoraRtcEngine2.h?

**Comment by plutoless** [comment]
i believe this header is no longer needed. could you pls try removing that include line and try again with latest sdk?

**Comment by yinkaisheng** [comment]
I need to comment the following two lines code if remove IAgoraRtcEngine2.h.	

```C++
IRtcEngine2 *lpRtcEngine2 = (IRtcEngine2 *)m_lpAgoraEngine;
int nRet = lpRtcEngine2->setVideoProfileEx(nWidth, nHeight, nFrameRate, nBitRate);
```
Now it compiles without errors.

**Comment by plutoless** [comment]
thanks @yinkaisheng  it would be great if you can raise a PR to remove these two lines and legacy header include.
