### ISSUE TITLE
Regarding a bug of Agora OpenDuo for iOS (Objective C)

### ISSUE THREAD

**Issue by simayang01** [AgoraIO/Advanced-Video#88]
We found a bug. That is, when an iPhone of iOS 13 Beta 7 is called at the first time, it receives the call properly. But after that, it can not receive any calling for the second, third and more times. Please view the video at the link below which shows the bug.

`http://1251260831.vod2.myqcloud.com/8f899cbcvodgzp1251260831/8fa49c725285890793128631286/3ejtvwW07CMA.mov`

**Comment by plutoless** [comment]
this only happens at iOS 13 beta 7?

**Comment by simayang01** [comment]
We tested only one single iPhone with iOS 13 Beta. The issue happens with Beta 7 and Beta 8 both.

**Comment by plutoless** [comment]
we did some quick test on non-beta versions and it's working fine. Could you pls try switching to non-beta devices and test on these?

**Comment by simayang01** [comment]
Then what if iOS is upgraded to iOS 13 one day?

**Comment by plutoless** [comment]
We will support official iOS13 when it comes out for sure, while we cannot guarantee to support beta versions as itself is not stable enough.
